apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-clusterrole-sa-binding
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  name: example-clusterrole
  kind: ClusterRole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: example-sa
    namespace: production
