apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-role-sa-binding
  namespace: production
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  name: example-role
  kind: Role
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: example-sa
    namespace: production
