apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-pvt-image
  name: hello-pvt-image
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: amitvashist7/apache-ex4
    name: hello-pvt-image
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
