apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  tolerations:
    - effect: "NoSchedule"
      key: "kubernetes.io/disk"
      operator: "Equal"
      value: "ssd"
  containers:
    - name: myapp
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
      ports:
        - containerPort: 80
