apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: production
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      name: frontend-app
      labels:
        app: frontend-app
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 128m
              memory: 256Mi
          ports:
            - containerPort: 8080
